describe('Flow Pagination', () => {
    it('passes', () => {
        const baseUrl = Cypress.config('baseUrl')
        cy.visit('/')
        cy.get('nav[role="navigation"]').should('be.visible')
        cy.get('ul[data-slot="wrapper"]').should('be.visible').trigger('mouseover')
        cy.get('li[aria-label="pagination item 1 active"').trigger('mouseover').should('have.text', '1')
        cy.get('li[aria-label="pagination item 2"]').trigger('mouseover').should('have.text', '2').click()
        cy.url().should('eq', baseUrl + '/?page=2')
        cy.get('li[aria-label="pagination item 2 active"').trigger('mouseover').should('have.text', '2')
        cy.get('li[aria-label="pagination item 3"]').trigger('mouseover').should('have.text', '3').click()
        cy.url().should('eq', baseUrl + '/?page=3')
        cy.get('li[aria-label="next page button"]').trigger('mouseover').click()
        cy.url().should('eq', baseUrl + '/?page=4')
        cy.get('li[aria-label="pagination item 4 active"').trigger('mouseover').should('have.text', '4')
        cy.get('li[aria-label="previous page button"]').trigger('mouseover').click()
        cy.url().should('eq', baseUrl + '/?page=3')
        cy.get('li[aria-label="pagination item 3 active"').trigger('mouseover').should('have.text', '3')
    })
})