import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../Provider/NextUiProvider";
import { ThemeProviders } from "../Provider/NextThemeProvider";
import Image from "next/image";
import MainLayout from "@/Layout/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Providers>
          <ThemeProviders>
            <MainLayout>
            <div className="hidden w-full h-full sm:flex">
              <Image
                alt="nextui logo"
                src={"/bg-right.webp"}
                width="0"
                height="0"
                sizes="100vw"
                className="w-full h-auto"
                priority
                style={{
                  zIndex: -100,
                  position: "fixed",
                  right: "-10%",
                  top: "-20%",
                  backgroundRepeat: "no-repeat",
                  backgroundPosition: "end",
                  transform: "scaleX(-1)",
                  width: "auto",
                  height: "auto",
                }}
              />
              <Image
                alt="nextui logo"
                src={"/bg-left.webp"}
                width="0"
                height="0"
                sizes="100vw"
                className="w-full h-auto"
                style={{
                  zIndex: -100,
                  position: "fixed",
                  left: "-10%",
                  bottom: "-20%",
                  backgroundRepeat: "no-repeat",
                  backgroundPosition: "end",
                  transform: "rotate(180deg)",
                  width: "auto",
                  height: "auto",
                }}
              />
            </div>
            {children}
            </MainLayout>
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  );
}
