import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../Provider/NextUiProvider";
import { ThemeProviders } from "../Provider/NextThemeProvider";
import MainLayout from "@/Layout/MainLayout";
import { BackgroundImage } from "@/Component/BackgroundImage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <Providers>
          <ThemeProviders>
            <MainLayout>
              <BackgroundImage />
              {children}
            </MainLayout>
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  );
}
